CREATE TABLE Articles
(
	Code	INT PRIMARY KEY IDENTITY (1,1)	NOT NULL,
	Name	NVARCHAR(50)				NOT NULL,
	Price	SMALLMONEY				NOT NULL,
	VAT	NUMERIC(3,2)				NOT NULL,
	Cost	SMALLMONEY				NOT NULL,
	Stock	INTEGER				NOT NULL
)

CREATE TABLE Sales
(
	Code	INT PRIMARY KEY IDENTITY (1,1)	NOT NULL,
	Time	SMALLDATETIME				NOT NULL
)

CREATE TABLE SalesDetails
(
	CodeSale	INT FOREIGN KEY REFERENCES Sales(Code)	NOT NULL,
	CodeArticle	INT FOREIGN KEY REFERENCES Articles(Code)		NOT NULL,
	Price		SMALLMONEY						NULL,
	VAT		NUMERIC(3,2)						NULL,	Quantity	INTEGER						NOT NULL

)

ALTER TABLE SalesDetails
ADD CONSTRAINT PK_SalesDetails PRIMARY KEY (CodeSale,CodeArticle)
